### ISSUE TITLE
Start action succeeds when sisyphus actually fails to start

### ISSUE THREAD

**Issue by cmars** [cloud-green/sisyphus#14]
I deployed the sisyphus charm and tried running the start action. It said:
```
ubuntu@chthonic:~/mojo/ua-event-bus/cdo/ua-event-bus/devel/configs$ juju run-action sisyphus/0 start --wait
unit-sisyphus-0:
  id: f1cf54fb-b893-40a1-878d-860303e2f93b
  status: completed
  timing:
    completed: 2019-06-14 16:53:30 +0000 UTC    enqueued: 2019-06-14 16:53:26 +0000 UTC
    started: 2019-06-14 16:53:29 +0000 UTC
  unit: sisyphus/0
```

However, I ssh'd onto the unit and found it was not running. I added a log line to the start action script to try and find out why, and discovered that sisyphus actually couldn't connect to kafka:

```
root@juju-ae4f51-8:~# /snap/bin/sisyphus -kafka-brokers 10.231.57.245:9093 -kafka-client-id sisyphus2 -workers 1 -kafka-cert /var/snap/sisyphus/common/client.crt -kafka-key /var/snap/sisyphus/common/client.key -kafka-ca /var/snap/sisyphus/common/ca.crt -config /var/snap/sisyphus/common/config.yaml -log-level DEBUG
{"level":"error","ts":"2019-06-14T17:11:55.582Z","msg":"failed to create kafka client","error":{"msg":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}}
```

These kinds of errors need to be surfaced when invoking the action. nohup may or may not be sufficient for this purpose. We could use systemd; `systemctl disable` will prevent sisyphus from auto-starting, while still allowing it to be started and stopped from the action with `systemctl start|stop`. `systemctl is-active` and `systemctl status` could be used to feed back action status.
